version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: '/app'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'yarn'
    directory: '/functions'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
