options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'NODE_ENV=$_NODE_ENV'
    - 'MONGO_DB_DATABASE_URL=$_MONGO_DB_DATABASE_URL'
    - 'STRIPE_WEBHOOK_SECRET=$_STRIPE_WEBHOOK_SECRET'
    - 'STRIPE_SECRET_KEY=$_STRIPE_SECRET_KEY'

timeout: '1600s'

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: install

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env']
    id: create-env
    waitFor: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    id: build
    waitFor: ['create-env']

  - name: 'bash'
    args: [cp, 'package.json', 'dist']
    id: move-package.json
    waitFor: ['build']

  - name: 'bash'
    args: [cp, 'package-lock.json', 'dist']
    id: move-package-lock.json
    waitFor: ['move-package.json']

  - name: 'bash'
    args: [rm, 'tsconfig.json']
    id: remove-tsconfig.json
    waitFor: ['move-package-lock.json']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ['remove-tsconfig.json']
    args:
      - gcloud
      - functions
      - deploy
      - stripe-webhook-9
      - --region=europe-west1
      - --source=dist
      - --trigger-http
      - --runtime=nodejs18
