options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'NODE_ENV=$_NODE_ENV'
    - 'MONGO_DB_DATABASE_URL=$_MONGO_DB_DATABASE_URL'
    - 'STRIPE_WEBHOOK_SECRET=$_STRIPE_WEBHOOK_SECRET'
    - 'STRIPE_SECRET_KEY=$_STRIPE_SECRET_KEY'

timeout: '1600s'

steps:
  - name: node:18.12.1
    dir: functions
    entrypoint: yarn
    args: ['install']
    id: install

  - name: node:18.12.1
    args: ['create-env']
    dir: functions
    entrypoint: yarn
    id: create-env
    waitFor: ['install']

  - name: node:18.12.1
    args: ['build']
    dir: functions
    entrypoint: yarn
    id: build
    waitFor: ['create-env']

  - name: bash
    dir: functions
    script: |
      #!/usr/bin/env bash
      mv package.json dist/package.json

    id: move-package.json
    waitFor: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: functions
    waitFor: ['move-package.json']
    args:
      - gcloud
      - functions
      - deploy
      - stripe-webhook-9
      - --region=europe-west1
      - --source=dist
      - --trigger-http
      - --runtime=nodejs18
