options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'NODE_ENV=$_NODE_ENV'
    - 'MONGO_DB_DATABASE_URL=$_MONGO_DB_DATABASE_URL'
    - 'STRIPE_WEBHOOK_SECRET=$_STRIPE_WEBHOOK_SECRET'
    - 'STRIPE_SECRET_KEY=$_STRIPE_SECRET_KEY'

timeout: '1600s'

steps:
  - name: node:18.12.1
    id: install
    dir: functions

    entrypoint: npm
    args: ['install']

  - name: node:18.12.1
    waitFor: ['install']

    id: create-env
    dir: functions

    entrypoint: npm
    args: ['run', 'create-env']

  - name: node:18.12.1
    waitFor: ['create-env']

    dir: functions
    id: build

    entrypoint: npm
    args: ['run', 'build']

  - name: bash
    waitFor: ['build']

    dir: functions
    id: move-package.json

    script: |
      #!/usr/bin/env bash
      mv package.json dist/package.json
      mv package-lock.json dist/package-lock.json
      mv tsconfig.json dist/tsconfig.json

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ['move-package.json']

    dir: functions
    args:
      - gcloud
      - functions
      - deploy
      - stripe-webhook-9
      - --region=europe-west1
      - --source=dist
      - --trigger-http
      - --runtime=nodejs18
