options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'NODE_ENV=$_NODE_ENV'
    - 'MONGO_DB_DATABASE_URL=$_MONGO_DB_DATABASE_URL'
    - 'STRIPE_WEBHOOK_SECRET=$_STRIPE_WEBHOOK_SECRET'
    - 'STRIPE_SECRET_KEY=$_STRIPE_SECRET_KEY'

timeout: '1600s'

steps:
  - name: node:18.12.1
    dir: functions
    entrypoint: yarn

  - name: node:18.12.1
    dir: functions
    entrypoint: yarn
    args: ['create-env']

  - name: node:18.12.1
    dir: functions
    entrypoint: yarn
    args: ['build']
