options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'

steps:
  - name: bash
    script: |
      #!/usr/bin/env bash
      cd app

  - name: node:18.12.1
    entrypoint: yarn
    args: ['install']

  - name: node:18.12.1
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - 'NODE_ENV                           = $_NODE_ENV'
      - 'DATABASE_URL                       = $_DATABASE_URL'
      - 'AUTH0_BASE_URL                     = $_AUTH0_BASE_URL'
      - 'AUTH0_BASE_URL                     = $_AUTH0_BASE_URL'
      - 'AUTH0_CLIENT_SECRET                = $_AUTH0_CLIENT_SECRET'
      - 'AUTH0_CLIENT_ID                    = $_AUTH0_CLIENT_ID'
      - 'AUTH0_ISSUER_BASE_URL              = $_AUTH0_ISSUER_BASE_URL'
      - 'AUTH0_SECRET                       = $_AUTH0_SECRET'
      - 'OPEN_AI_API_KEY                    = $_OPEN_AI_API_KEY'
      - 'OPEN_AI_BASE_URL                   = $_OPEN_AI_BASE_URL'
      - 'STRIPE_SECRET_KEY                  = $_STRIPE_SECRET_KEY'
      - 'PROJECT_ID                         = $_PROJECT_ID'
      - 'CLIENT_ID                          = $_CLIENT_ID'
      - 'CLIENT_EMAIL                       = $_CLIENT_EMAIL'
      - 'PRIVATE_KEY                        = $_PRIVATE_KEY'
      - 'BUCKET_NAME                        = $_BUCKET_NAME'
      - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = $_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'

  - name: node:18.12.1
    entrypoint: yarn
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
