service: ai-portrait-studio
runtime: nodejs18
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 30
  min_idle_instances: 0
  max_concurrent_requests: 700
  target_throughput_utilization: 0.8
