name: Build Next.js App

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

env:
  MONGO_DB_DATABASE_URL: ${{ secrets.MONGO_DB_DATABASE_URL }}
  AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
  GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
  GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
  GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
  OPEN_AI_BASE_URL: ${{ secrets.OPEN_AI_BASE_URL }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        working-directory: ./app
        run: yarn install

      - name: Build
        working-directory: ./app
        run: yarn build
